name: ca_tdd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^3.1.0
  flutter_bloc: ^3.0.0
  equatable: ^1.0.1
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  shared_preferences: ^0.5.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mockito: ^5.0.14

  flutter_lints: ^2.0.0
  build_runner: ^1.12.2
  mockito: ^5.0.7

flutter:
  uses-material-design: true
