// Mocks generated by Mockito 5.0.7 from annotations
// in ca_tdd/test/features/number_trivia/domain/usecases/get_concrete_number_trivia_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'get_concrete_number_trivia_test.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [MockNumberTriviaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockNumberTriviaRepository extends _i1.Mock
    implements _i2.MockNumberTriviaRepository {
  MockMockNumberTriviaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get hashCode =>
      (super.noSuchMethod(Invocation.getter(#hashCode), returnValue: 0) as int);
  @override
  bool operator ==(Object? other) =>
      (super.noSuchMethod(Invocation.method(#==, [other]), returnValue: false)
          as bool);
  @override
  String toString() =>
      (super.noSuchMethod(Invocation.method(#toString, []), returnValue: '')
          as String);
}
